### PR TITLE
improve readability

### PR DESCRIPTION
**Pull request by andrewferlitsch**

### CODE REVIEW

**Comment by nnegrey** [comment]
The current line matches our docs line: https://cloud.google.com/ml-engine/docs/prediction-overview. Though I'm not actually sure which is better. 

The `examples` doesn't seem quite right either.

**Comment by andrewferlitsch** [comment]
I am okay with your choice. My wording would be more inline if one was writing for a statistics audience.

**Comment by gogasca** [comment]
@andrewferlitsch LGTM "You can host your trained machine learning models on AI Platform for predictions (inference) from new examples".  maybe we can update docs as well?

**Comment by andrewferlitsch** [comment]
@gogasca I added you as a reviewer so you can approve the review. Sounds like the reference to updating the documentation should be a samples issue (rebecca)?

**Comment by gogasca** [comment]
> @gogasca I added you as a reviewer so you can approve the review. Sounds like the reference to updating the documentation should be a samples issue (rebecca)?

That would be @thedriftofwords

**Pull request merged**
