### PR TITLE
+x cleanup.sh & train-cloud.sh

### PR DESCRIPTION
**Pull request by AaronNBrock**
This is a really simple PR to makes the scripts inside `quickstart/scripts/*.sh` executable.

EDIT:  I made all of the `*.sh` files executable (even outside of `/quickstart/`)

### CODE REVIEW

**Comment by AaronNBrock** [comment]
@googlebot I signed it!

**Review by ivanmkc — APPROVED** [review]
LGTM

**Comment by thedriftofwords** [comment]
The Kokoro tests (for Python and notebook run) are not applicable to this PR, so I'll squash and merge now.

**Comment by thedriftofwords** [comment]
Thanks for your contribution, @AaronNBrock!

**Pull request merged**
