### PR TITLE
Andrewferlitsch custom

### PR DESCRIPTION
**Pull request by andrewferlitsch**
This is the draft.  I have the hooks into task.py to call custom.create() instead of model.create() for a custom tf.keras wide and deep model. It is enabled with the arg --custom_model

Not yet tested, since I am still figuring out the overall scripts.

### CODE REVIEW

**Comment by gogasca** [comment]
Some errors from pylint:

```
./trainer/custom.py:117:1: E302 expected 2 blank lines, found 1
1     E124 closing bracket does not match visual indentation
9     E128 continuation line under-indented for visual indent
4     E302 expected 2 blank lines, found 1
4     E501 line too long (92 > 80 characters)
1     F821 undefined name 'dropout'
1     F841 local variable 'n_classes' is assigned to but never used
6     W291 trailing whitespace
10    W293 blank line contains whitespace
```

**Comment by gogasca** [comment]
@andrewferlitsch is this PR still relevant?

**Comment by gogasca** [comment]
@andrewferlitsch ping

**Comment by andrewferlitsch** [comment]
@gogasca I recommend we close this "old" PR of mine. Thoughts?

**Pull request merged**
