### PR TITLE
fix dead link and missing content for generating codelab

### PR DESCRIPTION
**Pull request by mco-gh**
Please open your PR in [vertex-ai-samples](https://github.com/googlecloudplatform/vertex-ai-samples), if your PR creates new content or updates existing content on Vertex AI products. 

Before submitting a Jupyter notebook, follow this mandatory checklist:

- [ ] Use the [notebook template](https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/notebook_template.ipynb) as a starting point.
- [ ] Double check that all links, including the Colab and Github links to the notebook, are valid.
- [ ] Follow the style and grammar rules outlined in the above notebook template.
- [ ] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [ ] Passes all the required automated checks
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [ ] This notebook has been added to the CODEOWNERS file, pointing to the author or the author's team. If the CODEOWNERS file doesn't exist, create one in the nearest folder that makes sense.
- [ ] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

### CODE REVIEW

**Review by ivanmkc — CHANGES_REQUESTED** [review]
I think you have to run the linter. 

The current lint check is broken but I can see from the diff that the entire JSON has changed.

Also, can you make sure that the CODEOWNERS file includes this notebook?

**Comment by mco-gh** [comment]
Not sure why the whole json file changed. I cloned the repo and just added a comment block and fixed a missing link. Anyway I just ran the linter manually and afterward git diff shows nothing changed. Here's the linter output:

10:14:20 ai-platform-samples$ .github/workflows/linter/run_linter.sh
Test mode: false
Checking notebook: ai-platform-unified/notebooks/official/model_monitoring/model_monitoring.ipynb
Running black...
reformatted ai-platform-unified/notebooks/official/model_monitoring/model_monitoring.ipynb
All done! ✨ 🍰 ✨
1 file reformatted.
Running pyupgrade...
Running isort...
Fixing /privateai-platform-unified/notebooks/official/model_monitoring/model_monitoring.ipynb
Running nbfmt...
Format notebook: ai-platform-unified/notebooks/official/model_monitoring/model_monitoring.ipynb
Running flake8...
Notebook lint finished with return code = 0

All tests finished. Exiting with return code = 0
10:14:28 ai-platform-samples$ git diff
10:14:33 ai-platform-samples$

**Comment by mco-gh** [comment]
Per your request, I added myself as owner of this notebook in CODEOWNERS

**Comment by ivanmkc** [comment]
Thanks, it might not have been linted in the initial commit since the linter needs to be fixed (PR is already open for it). I'll approve based on your comments.

**Review by ivanmkc — APPROVED** [review]
LGTM

**Comment by mco-gh** [comment]
Thanks!

**Pull request merged**
