### PR TITLE
pip3 instead of pip

### PR DESCRIPTION
**Pull request by JoshuaFox**
In  general pip3 is  used, correctly; but in two places pip is used. Changed these two to pip3

### CODE REVIEW

**Review by ivanmkc — APPROVED** [review]
LGTM

**Comment by JoshuaFox** [comment]
It turns out that though I have the CLA, that is not recognized because I am following Github best practice of exposing only an anonymized email address.

Let me know if you want me to switch to exposing my underlying email address and submit a new PR or if you prefer to out this through yourselves (it's just two characters of change.)

**Comment by ivanmkc** [comment]
@JoshuaFox I'm comfortable admin merging this. Thanks for the fix!

**Pull request merged**
