### PR TITLE
Fork the reduction server example for AI Platform

### PR DESCRIPTION
**Pull request by changlan**
Adapted from ai-platform-unified/notebooks/unofficial/reduction_server

### CODE REVIEW

**Review by morgandu — CHANGES_REQUESTED** [review]
Hello, we are migrating the content to [GoogleCloudPlatform/vertex-ai-samples](https://github.com/googlecloudplatform/vertex-ai-samples/). Everything under [ai-platform-samples/ai-platform-unified](https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/ai-platform-unified) is moved over, and `ai-platform-unified/` directory will soon be archived/deleted.

**Comment by changlan** [comment]
Hi @morgandu, this notebook is for the legacy AI Platform. Should it stay in this repo or be moved to GoogleCloudPlatform/vertex-ai-samples?

**Review by morgandu — APPROVED** [review]

**Comment by morgandu** [comment]
> Hi @morgandu, this notebook is for the legacy AI Platform. Should it stay in this repo or be moved to GoogleCloudPlatform/vertex-ai-samples?

My bad, `ai-platform/` should stay in this repo!

**Comment by nikitamaia** [comment]
LGTM!

**Comment by changlan** [comment]
Could anyone merge the PR? I don't have permission for this repo :) Thanks!

**Comment by nikitamaia** [comment]
@ivanmkc can you take a quick look? This is the Reduction Server notebook but for AI Platform in case we have users who haven't migrated yet but still want to try the feature.

**Comment by changlan** [comment]
ping @nikitamaia @ivanmkc

**Pull request merged**
