### PR TITLE
feat: XAI notebooks

### PR DESCRIPTION
**Pull request by andrewferlitsch**

### CODE REVIEW

**Comment by andrewferlitsch** [comment]
moving the notebooks

**Comment by ivanmkc** [comment]
For notebooks, you don't need a code review as long as the TW signs off on it.

There are some markdown sections that are a little verbose, so please see https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/official/custom-training-online-prediction.ipynb for pared down versions of the same sections.

**Comment by andrewferlitsch** [comment]
I am closing this PR due to other commits that were not meant to be part of this PR

**Pull request closed without merging**
