### PR TITLE
Add sample notebook for XGBoost AI Hub component

### PR DESCRIPTION
**Pull request by David-LiCause**
This PR includes a sample notebook for training a model using the [XGBoost AI Hub component](https://aihub.cloud.google.com/u/0/p/products%2F0ccd8a63-71a7-4e48-a68b-685692a62e92) with the AI Platform Training and Prediction services

### CODE REVIEW

**Comment by gogasca** [comment]
@David-LiCause we are looking into this, we will get back to you

**Comment by David-LiCause** [comment]
> @David-LiCause we are looking into this, we will get back to you

@gogasca Thanks

**Comment by David-LiCause** [comment]
@gogasca Thanks for reviewing this! I'll update the PR

**Comment by gogasca** [comment]
> @gogasca Thanks for reviewing this! I'll update the PR

Sounds good. Thanks

**Comment by David-LiCause** [comment]
@gogasca These changes are ready to be reviewed when you have time. Let me know if you need me to make any additional changes

**Comment by gogasca** [comment]
Hi @David-LiCause, I just agreed that since we will be having 10 AI Hub notebooks, it makes sense to keep them together, once last change before I merge: Move this notebook to this location ai-platform-samples/notebooks/samples/aihub/house_prices/current_notebook_name.ipynb

Thanks

**Comment by David-LiCause** [comment]
@gogasca I just moved the XGBoost notebook to the aihub folder. If you need any additional changes just let me know. Thanks

**Pull request merged**
