### PR TITLE
Writing edits for online prediction notebook

### PR DESCRIPTION
**Pull request by thedriftofwords**
Also includes changes by @ivanmkc in the model deployment section, replacing the `deploy_model` helper function with the model.deploy method.

### CODE REVIEW

**Review by ivanmkc — APPROVED** [review]
LGTM

**Review by ivanmkc — CHANGES_REQUESTED** [review]
Can you fix the Colab and Github link as well to point to the current location?

**Comment by thedriftofwords** [comment]
> Can you fix the Colab and Github link as well to point to the current location?

Done, thanks!

**Review by ivanmkc — APPROVED** [review]
LGTM

**Pull request merged**
