### PR TITLE
Factorization Machines classification example

### PR DESCRIPTION
**Pull request by post2web**
This is the first of 13 AI Hub example notebooks that we'd like to contribute. They all show the use of [AI Hub ML Containers](https://aihub.cloud.google.com/u/0/s?category=ml-container)

### CODE REVIEW

**Comment by gogasca** [comment]
<p>I noticed you also uploaded a second file, (checkpoint) I think is ok to remove it.</p><p> </p>

**Comment by gogasca** [comment]
<p>We just started a new Notebook contribution process: The idea is to standardize the notebooks across AI Platform.</p><p>We created a new template for Notebooks which includes a template for AI Platform and other for AI Platform/Colab.</p><p><a href="https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/notebooks/templates" target="_blank">https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/notebooks/templates</a></p><p>This is the first Notebook PR request we get in this repo, so please bear with us in the review process.</p><p>Suggestions:</p><ol><li>Can you please move to this template?</li><li>Move this notebook to this location ai-platform-samples/notebooks/samples/tensorflow/<a href="https://github.com/GoogleCloudPlatform/ai-platform-samples/pull/101/files#diff-be2cca3cd466d551b13a15d8b7b456fa" target="_blank">factorization_machines_classification</a>/current_notebook_name.ipynb</li></ol><pre class="ql-syntax" spellcheck="false">.
     ├── datasets
     └── notebooks
         └── samples
             ├── tensorflow                           
                └── factorization_machines_classification
</pre><p> </p><p>My understanding is the container uses TF?</p>

**Comment by post2web** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/GoogleCloudPlatform/ai-platform-samples/pull/101/discussion/) on ReviewNB
> 
> _gogasca commented on 2020-02-21T17:58:30Z_
> ----------------------------------------------------------------
> 
> Can we use latest version 1.15?

The container uses TF1.4 and for that reason, I have runtime 1.4. I believe 1.15 should work as well. Do you prefer if I set 1.15 instead?

**Comment by post2web** [comment]
> We just started a new Notebook contribution process: The idea is to standardize the notebooks across AI Platform.
> 
> We created a new template for Notebooks which includes a template for AI Platform and other for AI Platform/Colab.
> 
> https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/notebooks/templates
> 
> This is the first Notebook PR request we get in this repo, so please bear with us in the review process.
> 
> Suggestions:
> 
> 1. Can you please move to this template?
> 2. Move this notebook to this location ai-platform-samples/notebooks/samples/tensorflow/[factorization_machines_classification](https://github.com/GoogleCloudPlatform/ai-platform-samples/pull/101/files#diff-be2cca3cd466d551b13a15d8b7b456fa)/current_notebook_name.ipynb
> 
> .
>      ├── datasets
>      └── notebooks
>          └── samples
>              ├── tensorflow                           
>                 └── factorization_machines_classification
> My understanding is the container uses TF?

This template is one out of 13. They all show the same workflow. All except 4 are TF components. To me, it makes more sense to have them all in `aihub` instead of group them by framework but I can put them in framework folders if you prefer.

Just a heads-up, the notebooks that we'd like to submit are:
- PCA (TensorFlow)
- KMeans (TensorFlow)
- KNN  (Fias)	Classification and Regression (2 different notebooks)
- Factorization Machines  (TensorFlow)	Classification and Regression (2 different notebooks)
- Tabular Anomaly Detection  (TensorFlow)
- XGBoost (XGBoost)	Classification and Regression (2 different notebooks)
- TF Module image (TensorFlow)	Image classification
- ResNet (TensorFlow)	Image classification
- RetinaNet (TensorFlow)	Object detection
- Tabular Data Inspection (pandas profiling)	Visualize data statistics

**Comment by gogasca** [comment]
<p>@postweb, thanks for the info, ok having the aihub folder makes sense now. Only requirement from our side would be have an individual folder per notebook.</p><p> </p><p>Thanks </p><p> </p>

**Pull request merged**
