### PR TITLE
remove user prompt while installing sysstat

### PR DESCRIPTION
**Pull request by vchandvankar**
We would like to install the script without a user prompt

### CODE REVIEW

**Comment by gogasca** [comment]
Can you sign the CLA please?

**Comment by gogasca** [comment]
@vchandvankar ping

**Comment by vchandvankar** [comment]
Apologies for the delay @gogasca, i kept missing notifications on my email.
I have signed the CLA

**Comment by gogasca** [comment]
> Apologies for the delay @gogasca, i kept missing notifications on my email.
> I have signed the CLA

I think you need to reply: 

"""Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.""" to update the checks

**Pull request merged**
