### PR TITLE
Keras Census Dataset replacement

### PR DESCRIPTION
**Pull request by aribray**
Moving changes from `cloudml-samples` repo to `ai-platform-samples` repo

### CODE REVIEW

**Comment by ivanmkc** [comment]
Since this is a training sample and not a notebook, you'll have to check with @morgandu about where this should live exactly.

One idea is 'REPO_ROOT/ai-platform/tutorials/...'

**Comment by ivanmkc** [comment]
@aribray Can you confirm if you've tested this following the instructions from the tutorial and that it works correctly with the Penguin changes?

**Comment by ivanmkc** [comment]
I've tested it before but that was before you switched to the new version of the Penguin dataset, which had different columns.

**Comment by aribray** [comment]
> I've tested it before but that was before you switched to the new version of the Penguin dataset, which had different columns.

Yep, it worked. I just had to adjust the `species` column, so we should be good to go

**Review by morgandu — APPROVED** [review]

**Pull request merged**
